version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: audit_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/audit_auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres

  analysis-service:
    build: ./analysis-service
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
    depends_on:
      - auth-service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_AUTH_SERVICE_URL=http://localhost:8081
      - REACT_APP_ANALYSIS_SERVICE_URL=http://localhost:8000
    depends_on:
      - auth-service
      - analysis-service

volumes:
  postgres_data: 